#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Environment Setup Script for Terraform Backend

.DESCRIPTION
    This script generates environment-specific tfvars files for Terraform.
    Backend creation is done via Terraform migration approach.
    See SETUP_GUIDE.md for the complete workflow.

.PARAMETER Environment
    The environment to configure: dev, qa, or pro

.EXAMPLE
    .\setup-environment.ps1 dev     # Generate dev.tfvars
    .\setup-environment.ps1 qa      # Generate qa.tfvars
    .\setup-environment.ps1 pro     # Generate pro.tfvars
#>

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("dev", "qa", "pro")]
    [string]$Environment
)

$ErrorActionPreference = "Stop"

# Configuration (can be overridden with environment variables)
$BASE_BUCKET = if ($env:TF_STATE_BUCKET_NAME) { $env:TF_STATE_BUCKET_NAME } else { "victorgalantech-tfstate" }
$BASE_TABLE = if ($env:TF_LOCK_DYNAMODB_TABLE_NAME) { $env:TF_LOCK_DYNAMODB_TABLE_NAME } else { "terraform-state-locks" }
$REGION = if ($env:AWS_REGION) { $env:AWS_REGION } else { "eu-west-1" }

# Backend naming with environment suffix
$BACKEND_BUCKET = "${BASE_BUCKET}-${Environment}"
$BACKEND_TABLE = "${BASE_TABLE}"

# Determine script directory and project root
$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$PROJECT_ROOT = Split-Path -Parent $SCRIPT_DIR
$TERRAFORM_DIR = Join-Path $PROJECT_ROOT "terraform"

#==============================================================================
# Function: Generate tfvars
#==============================================================================
function New-TfVars {
    Write-Host ""
    Write-Host "╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Blue
    Write-Host "║              Generating tfvars for $($Environment.ToUpper()) Environment              ║" -ForegroundColor Blue
    Write-Host "╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Blue
    Write-Host ""
    
    $TFVARS_FILE = Join-Path $TERRAFORM_DIR "${Environment}.tfvars"
    
    Write-Host "Creating: $TFVARS_FILE"
    Write-Host ""
    Write-Host "Configuration:"
    Write-Host "  Environment: $Environment"
    Write-Host "  Bucket:      $BACKEND_BUCKET"
    Write-Host "  Table:       $BACKEND_TABLE"
    Write-Host "  Region:      $REGION"
    Write-Host ""
    
    $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss UTC")
    
    $content = @"
# Environment: $Environment
# Generated by: scripts\setup-environment.ps1
# Date: $timestamp

# Environment name (dev, qa, or pro)
environment = "$Environment"

# AWS region for all resources
aws_region = "$REGION"

# S3 Bucket Name (REQUIRED)
# This must be globally unique across all AWS accounts
# Format: base-name-environment (e.g., victorgalantech-tfstate-dev)
bucket_name = "$BACKEND_BUCKET"

# DynamoDB Table for State Locking (REQUIRED)
# Shared across environments for simplicity
TF_LOCK_DYNAMODB_TABLE_NAME = "$BACKEND_TABLE"

# Optional: Override lifecycle retention (default: 90 days)
# noncurrent_version_expiration_days = 90

# Optional: Add custom tags
# tags = {
#   Project     = "Infrastructure"
#   ManagedBy   = "Terraform"
#   CostCenter  = "Engineering"
# }
"@
    
    Set-Content -Path $TFVARS_FILE -Value $content -Encoding UTF8
    
    Write-Host "✅ Created: $TFVARS_FILE" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next: Follow Backend Migration workflow" -ForegroundColor Yellow
    Write-Host "See: SETUP_GUIDE.md for complete steps"
    Write-Host ""
    Write-Host "Quick summary:"
    Write-Host "  1. terraform init                              # Local state"
    Write-Host "  2. terraform apply -var-file=$Environment.tfvars     # Create backend"
    Write-Host "  3. (Uncomment backend block in backend.tf)"
    Write-Host "  4. terraform init -backend-config=backend-$Environment.hcl -migrate-state"
    Write-Host ""
}

#==============================================================================
# Main
#==============================================================================

New-TfVars
