#!/bin/bash
set -e

#==============================================================================
# Environment Setup Script
# 
# This script generates environment-specific tfvars files for Terraform.
#
# Backend creation is done via Terraform migration approach.
# See SETUP_GUIDE.md for the complete workflow.
#
# Usage:
#   ./setup-environment.sh <environment>
#
# Arguments:
#   environment: dev, qa, or pro
#
# Examples:
#   ./setup-environment.sh dev     # Generate dev.tfvars
#   ./setup-environment.sh qa      # Generate qa.tfvars
#   ./setup-environment.sh pro     # Generate pro.tfvars
#==============================================================================

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
ENV=$1

# Validation
if [ -z "$ENV" ]; then
  echo -e "${RED}Error: Environment argument is required${NC}"
  echo ""
  echo "Usage: $0 <dev|qa|pro>"
  echo ""
  echo "Examples:"
  echo "  $0 dev     # Generate dev.tfvars"
  echo "  $0 qa      # Generate qa.tfvars"
  echo "  $0 pro     # Generate pro.tfvars"
  echo ""
  echo "For backend creation, see SETUP_GUIDE.md"
  exit 1
fi

if [[ ! "$ENV" =~ ^(dev|qa|pro)$ ]]; then
  echo -e "${RED}Error: Environment must be 'dev', 'qa', or 'pro'${NC}"
  exit 1
fi

# Configuration (can be overridden with environment variables)
BASE_BUCKET="${TF_STATE_BUCKET_NAME:-victorgalantech-tfstate}"
BASE_TABLE="${TF_LOCK_DYNAMODB_TABLE_NAME:-terraform-state-locks}"
REGION="${AWS_REGION:-eu-west-1}"

# Backend naming with environment suffix
BACKEND_BUCKET="${BASE_BUCKET}-${ENV}"
BACKEND_TABLE="${BASE_TABLE}"

# Determine script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TERRAFORM_DIR="${PROJECT_ROOT}/terraform"


#==============================================================================
# Function: Generate tfvars
#==============================================================================
generate_tfvars() {
  echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${BLUE}║              Generating tfvars for ${ENV^^} Environment              ║${NC}"
  echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════╝${NC}"
  echo ""
  
  TFVARS_FILE="${TERRAFORM_DIR}/${ENV}.tfvars"
  
  echo "Creating: ${TFVARS_FILE}"
  echo ""
  echo "Configuration:"
  echo "  Environment: ${ENV}"
  echo "  Bucket:      ${BACKEND_BUCKET}"
  echo "  Table:       ${BACKEND_TABLE}"
  echo "  Region:      ${REGION}"
  echo ""
  
  cat > "${TFVARS_FILE}" <<EOF
# Environment: ${ENV}
# Generated by: scripts/setup-environment.sh
# Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Environment name (dev, qa, or pro)
environment = "${ENV}"

# AWS region for all resources
aws_region = "${REGION}"

# S3 Bucket Name (REQUIRED)
# This must be globally unique across all AWS accounts
# Format: base-name-environment (e.g., victorgalantech-tfstate-dev)
bucket_name = "${BACKEND_BUCKET}"

# DynamoDB Table for State Locking (REQUIRED)
# Shared across environments for simplicity
TF_LOCK_DYNAMODB_TABLE_NAME = "${BACKEND_TABLE}"

# Optional: Override lifecycle retention (default: 90 days)
# noncurrent_version_expiration_days = 90

# Optional: Add custom tags
# tags = {
#   Project     = "Infrastructure"
#   ManagedBy   = "Terraform"
#   CostCenter  = "Engineering"
# }
EOF
  
  echo -e "${GREEN}✅ Created: ${TFVARS_FILE}${NC}"
  echo ""
  echo -e "${YELLOW}Next: Follow Backend Migration workflow${NC}"
  echo "See: SETUP_GUIDE.md for complete steps"
  echo ""
  echo "Quick summary:"
  echo "  1. terraform init                              # Local state"
  echo "  2. terraform apply -var-file=${ENV}.tfvars     # Create backend"
  echo "  3. (Uncomment backend block in backend.tf)"
  echo "  4. terraform init -backend-config=backend-${ENV}.hcl -migrate-state"
  echo ""
}

#==============================================================================
# Main
#==============================================================================

generate_tfvars
